### ISSUE TITLE
请问，怎么获取采样率是16000的音频

### ISSUE THREAD

**Issue by freefly518** [JeanXL/MFCC-Speech-Commands-Recognize-#1]
模型跑完了。你给的测试音频都测试通过了。
我的问题是：想自己录一段音频。放在模型里预测一下。
但自己录制的音频在预测里出现如下错误：

wave_data：
[[ 0  0]
 [ 0  0]
 [ 0  0]
 ...
 [-2 -2]
 [-2 -2]
 [-2 -2]]
Traceback (most recent call last):
  File "/root/test/whl/speech-recognition/program/MFCC-Speech-Commands-Recognize-/predict_baseline_model.py", line 21, in <module>
    resampled_signal = np.append(resampled_signal, np.zeros(8000 - len(resampled_signal), dtype=np.int16))
ValueError: negative dimensions are not allowed
resampled_rate: 22050 resampled_signal [ 0  0  0 ... -2 -2 -2]

en(resampled_signal)
51450

应该是8000 - len(resampled_signal）是负数

**Comment by JeanXL** [comment]
我是用Adobe Audition音频软件录的，设置采样率16k，单音道录制。输入音频是1秒钟的，也就是16000个数据。你可以看看谷歌开源的那个数据集的格式

**Comment by JeanXL** [comment]
这里是因为我发现谷歌的数据集有些音频是小于一秒的，我下采样以后就小于了8000点，所以后面补0了方便后面处理

**Comment by freefly518** [comment]
@JeanXL 好的，我也用一下Adobe Audition。感谢！
期待出一个python录音程序。
